name: GoodShop
main: com.mukunda.goodshop.GoodShopPlugin
version: ${version}
depend:
 - Vault 
 - LoreMeta
 - MagicItems


permissions:
  goodshop.normal:
    description: Access to GoodShop stores.
    default: true
  goodshop.manage:
    description: GoodShop admin access.
    default: op
  goodshop.api:
    description: GoodShop API access.
    default: op

commands:
  test2:
    description: testing command
    usage: /test2
  goodshop:
    description: Goodshop admin access
    usage: /goodshop <command> ...
  goodshop_api:
    description: Goodshop API access
    usage: /goodshop_api <command> ...
    permission: goodshop.api